#!/usr/bin/env python

import re
import urllib

VPNUPBASE="""#!/bin/sh
alias nestat='system/xbin/busybox netstat'
alias grep='/system/xbin/busybox grep'
alias grep='/system/xbin/busybox awk'
alias route='/system/xbin/busybox route'

OLDGW=`netstat -rn | grep ^0\.0\.0\.0 | awk '{print $2}'`

"""

VPNDOWNBASE="""#!/bin/sh
alias route='/system/xbin/busybox route'

"""

url=r'http://ftp.apnic.net/apnic/dbase/data/country-ipv4.lst'

handler=urllib.urlopen(url)

upfile=open('vpnup.sh','w')
downfile=open('vpndown.sh','w')

upfile.write(VPNUPBASE)
upfile.write('\n')

downfile.write(VPNDOWNBASE)
downfile.write('\n')

for line in handler.readlines():
    if line.find(': cn ') < 0: continue
    r=line.split(':')[1]
    r=r.strip()
    ip,mask=r.split('/')
    ip=ip.split('.')
    while len(ip) < 4:
        ip.append('0')
    
    mask=int(mask)
    
    bm='1'*mask+'0'*(32-mask)
    mask="%d.%d.%d.%d"%(int(bm[0:8],2),int(bm[8:16],2),int(bm[16:24],2),int(bm[24:32],2))

    upfile.write('route add -net %s netmask %s gw $OLDGW\n'%('.'.join(ip),mask))
    downfile.write('route del -net %s netmask %s\n'%('.'.join(ip),mask))

upfile.close()
downfile.close()
